// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/geoffjay/agar/cmd/agar/baml_client/stream_types"
	"github.com/geoffjay/agar/cmd/agar/baml_client/types"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsError   bool
	Error     error
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
	return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
	return s.as_stream
}

// / Streaming version of AgentPrompt
func (*stream) AgentPrompt(ctx context.Context, user_input string, conversation_history []types.ConversationMessage, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.AgentResponse, types.AgentResponse], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_input": user_input, "conversation_history": conversation_history},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AgentPrompt: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AgentPrompt", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.AgentResponse, types.AgentResponse])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.AgentResponse, types.AgentResponse]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.AgentResponse)
				channel <- StreamValue[stream_types.AgentResponse, types.AgentResponse]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.AgentResponse)
				channel <- StreamValue[stream_types.AgentResponse, types.AgentResponse]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of CreateAgarApp
func (*stream) CreateAgarApp(ctx context.Context, requirements string, project_name string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.AgarAppConfig, types.AgarAppConfig], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"requirements": requirements, "project_name": project_name},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: CreateAgarApp: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "CreateAgarApp", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.AgarAppConfig, types.AgarAppConfig])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.AgarAppConfig, types.AgarAppConfig]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.AgarAppConfig)
				channel <- StreamValue[stream_types.AgarAppConfig, types.AgarAppConfig]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.AgarAppConfig)
				channel <- StreamValue[stream_types.AgarAppConfig, types.AgarAppConfig]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateMainGo
func (*stream) GenerateMainGo(ctx context.Context, config types.AgarAppConfig, opts ...CallOptionFunc) (<-chan StreamValue[string, string], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"config": config},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateMainGo: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateMainGo", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[string, string])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[string, string]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(string)
				channel <- StreamValue[string, string]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(string)
				channel <- StreamValue[string, string]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateProjectStructure
func (*stream) GenerateProjectStructure(ctx context.Context, config types.AgarAppConfig, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.ProjectStructure, types.ProjectStructure], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"config": config},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateProjectStructure: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateProjectStructure", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.ProjectStructure, types.ProjectStructure])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.ProjectStructure, types.ProjectStructure]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.ProjectStructure)
				channel <- StreamValue[stream_types.ProjectStructure, types.ProjectStructure]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.ProjectStructure)
				channel <- StreamValue[stream_types.ProjectStructure, types.ProjectStructure]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}
