// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/geoffjay/agar/cmd/agar/baml_client/types"
)

func AgentPrompt(ctx context.Context, user_input string, conversation_history []types.ConversationMessage, opts ...CallOptionFunc) (types.AgentResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_input": user_input, "conversation_history": conversation_history},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "AgentPrompt", encoded, callOpts.onTick)
		if err != nil {
			return types.AgentResponse{}, err
		}

		if result.Error != nil {
			return types.AgentResponse{}, result.Error
		}

		casted := (result.Data).(types.AgentResponse)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "AgentPrompt", encoded, callOpts.onTick)
		if err != nil {
			return types.AgentResponse{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.AgentResponse{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.AgentResponse), nil
			}
		}

		return types.AgentResponse{}, fmt.Errorf("No data returned from stream")
	}
}

func CreateAgarApp(ctx context.Context, requirements string, project_name string, opts ...CallOptionFunc) (types.AgarAppConfig, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"requirements": requirements, "project_name": project_name},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "CreateAgarApp", encoded, callOpts.onTick)
		if err != nil {
			return types.AgarAppConfig{}, err
		}

		if result.Error != nil {
			return types.AgarAppConfig{}, result.Error
		}

		casted := (result.Data).(types.AgarAppConfig)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "CreateAgarApp", encoded, callOpts.onTick)
		if err != nil {
			return types.AgarAppConfig{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.AgarAppConfig{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.AgarAppConfig), nil
			}
		}

		return types.AgarAppConfig{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateMainGo(ctx context.Context, config types.AgarAppConfig, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"config": config},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateMainGo", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateMainGo", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}

func GenerateProjectStructure(ctx context.Context, config types.AgarAppConfig, opts ...CallOptionFunc) (types.ProjectStructure, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"config": config},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateProjectStructure", encoded, callOpts.onTick)
		if err != nil {
			return types.ProjectStructure{}, err
		}

		if result.Error != nil {
			return types.ProjectStructure{}, result.Error
		}

		casted := (result.Data).(types.ProjectStructure)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateProjectStructure", encoded, callOpts.onTick)
		if err != nil {
			return types.ProjectStructure{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ProjectStructure{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ProjectStructure), nil
			}
		}

		return types.ProjectStructure{}, fmt.Errorf("No data returned from stream")
	}
}
