// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/geoffjay/agar/cmd/agar/baml_client/stream_types"
	"github.com/geoffjay/agar/cmd/agar/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AgarAppConfig":              reflect.TypeOf(types.AgarAppConfig{}),
	"STREAM_TYPES.AgarAppConfig":       reflect.TypeOf(stream_types.AgarAppConfig{}),
	"TYPES.AgentResponse":              reflect.TypeOf(types.AgentResponse{}),
	"STREAM_TYPES.AgentResponse":       reflect.TypeOf(stream_types.AgentResponse{}),
	"TYPES.ComponentConfig":            reflect.TypeOf(types.ComponentConfig{}),
	"STREAM_TYPES.ComponentConfig":     reflect.TypeOf(stream_types.ComponentConfig{}),
	"TYPES.ConversationMessage":        reflect.TypeOf(types.ConversationMessage{}),
	"STREAM_TYPES.ConversationMessage": reflect.TypeOf(stream_types.ConversationMessage{}),
	"TYPES.FileSpec":                   reflect.TypeOf(types.FileSpec{}),
	"STREAM_TYPES.FileSpec":            reflect.TypeOf(stream_types.FileSpec{}),
	"TYPES.MainStructure":              reflect.TypeOf(types.MainStructure{}),
	"STREAM_TYPES.MainStructure":       reflect.TypeOf(stream_types.MainStructure{}),
	"TYPES.ProjectStructure":           reflect.TypeOf(types.ProjectStructure{}),
	"STREAM_TYPES.ProjectStructure":    reflect.TypeOf(stream_types.ProjectStructure{}),
	"TYPES.ToolConfig":                 reflect.TypeOf(types.ToolConfig{}),
	"STREAM_TYPES.ToolConfig":          reflect.TypeOf(stream_types.ToolConfig{}),
}
