// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AgarAppConfigClassView struct {
	inner baml.ClassBuilder
}

func (t *AgarAppConfigClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AgarAppConfigClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *AgarAppConfigClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *AgarAppConfigClassView) PropertyModule_path() (ClassPropertyView, error) {
	return t.inner.Property("module_path")
}

func (t *AgarAppConfigClassView) PropertyTools() (ClassPropertyView, error) {
	return t.inner.Property("tools")
}

func (t *AgarAppConfigClassView) PropertyComponents() (ClassPropertyView, error) {
	return t.inner.Property("components")
}

func (t *AgarAppConfigClassView) PropertyFeatures() (ClassPropertyView, error) {
	return t.inner.Property("features")
}

func (t *AgarAppConfigClassView) PropertyMain_structure() (ClassPropertyView, error) {
	return t.inner.Property("main_structure")
}

func (t *TypeBuilder) AgarAppConfig() (*AgarAppConfigClassView, error) {
	bld, err := t.inner.Class("AgarAppConfig")
	if err != nil {
		return nil, err
	}
	return &AgarAppConfigClassView{inner: bld}, nil
}

func (t *AgarAppConfigClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ComponentConfigClassView struct {
	inner baml.ClassBuilder
}

func (t *ComponentConfigClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComponentConfigClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ComponentConfigClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ComponentConfigClassView) PropertyConfig() (ClassPropertyView, error) {
	return t.inner.Property("config")
}

func (t *TypeBuilder) ComponentConfig() (*ComponentConfigClassView, error) {
	bld, err := t.inner.Class("ComponentConfig")
	if err != nil {
		return nil, err
	}
	return &ComponentConfigClassView{inner: bld}, nil
}

func (t *ComponentConfigClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileSpecClassView struct {
	inner baml.ClassBuilder
}

func (t *FileSpecClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileSpecClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *FileSpecClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *FileSpecClassView) PropertyPurpose() (ClassPropertyView, error) {
	return t.inner.Property("purpose")
}

func (t *TypeBuilder) FileSpec() (*FileSpecClassView, error) {
	bld, err := t.inner.Class("FileSpec")
	if err != nil {
		return nil, err
	}
	return &FileSpecClassView{inner: bld}, nil
}

func (t *FileSpecClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MainStructureClassView struct {
	inner baml.ClassBuilder
}

func (t *MainStructureClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MainStructureClassView) PropertyUse_tui() (ClassPropertyView, error) {
	return t.inner.Property("use_tui")
}

func (t *MainStructureClassView) PropertyEntry_point() (ClassPropertyView, error) {
	return t.inner.Property("entry_point")
}

func (t *MainStructureClassView) PropertyInitialization() (ClassPropertyView, error) {
	return t.inner.Property("initialization")
}

func (t *TypeBuilder) MainStructure() (*MainStructureClassView, error) {
	bld, err := t.inner.Class("MainStructure")
	if err != nil {
		return nil, err
	}
	return &MainStructureClassView{inner: bld}, nil
}

func (t *MainStructureClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ProjectStructureClassView struct {
	inner baml.ClassBuilder
}

func (t *ProjectStructureClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ProjectStructureClassView) PropertyDirectories() (ClassPropertyView, error) {
	return t.inner.Property("directories")
}

func (t *ProjectStructureClassView) PropertyFiles() (ClassPropertyView, error) {
	return t.inner.Property("files")
}

func (t *ProjectStructureClassView) PropertyDependencies() (ClassPropertyView, error) {
	return t.inner.Property("dependencies")
}

func (t *TypeBuilder) ProjectStructure() (*ProjectStructureClassView, error) {
	bld, err := t.inner.Class("ProjectStructure")
	if err != nil {
		return nil, err
	}
	return &ProjectStructureClassView{inner: bld}, nil
}

func (t *ProjectStructureClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ToolConfigClassView struct {
	inner baml.ClassBuilder
}

func (t *ToolConfigClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ToolConfigClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ToolConfigClassView) PropertyPurpose() (ClassPropertyView, error) {
	return t.inner.Property("purpose")
}

func (t *ToolConfigClassView) PropertyCustom_config() (ClassPropertyView, error) {
	return t.inner.Property("custom_config")
}

func (t *TypeBuilder) ToolConfig() (*ToolConfigClassView, error) {
	bld, err := t.inner.Class("ToolConfig")
	if err != nil {
		return nil, err
	}
	return &ToolConfigClassView{inner: bld}, nil
}

func (t *ToolConfigClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
